services:
  frontend:
    build: 
      context: ./devopsapp
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3100:3100"
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod

networks:
  app-network:
  